language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
  - server/node_modules
  - client/node_modules

jobs:
  include:
    - stage: Test, Build, and Deploy
      branches:
        only:
        - master
        - deploy-to-prod
      script:
      - yarn test
      - yarn build
      deploy: &heroku
        provider: heroku
        app: my-feedback-team-b-staging
        api_key:
          secure: kJeZMjCpalowRjzBtGtQKhQGO1rjaL9Gn7jbZBnSiq2dfeq/2aCSKBtfQXmRGopaOQ/3uQju3spF7c3CPclXNkP7HFnEJ5nsuKVFd0xmdZIjnqorcdQCtAX3ogschHkjJkYRr/ffo2INGB9Mrht4UwGqrLJE7YMH6CG9sfCg/mfTMJNBa6cl3hHdVHlPl3hSOSPLF4q1+JKOolsZJt030CJKsw7jvJBA6ZhhLJqjDa3Ot66VxlPLsicXD2QCFTWBnfe59zKr1uHhtEUqqCxwiD2JLCXncrxKvCnHI7lzmL6xhBf6hoSbrn9ri43tbXK9YIKbOcbn/4k7CahsXgHb40cHahCYyQ9Kmta3vTY9ooEJqu66aqf3mykznqDRDlEflT6/chKJOG4NZpBPaHGhCWvzdFxIo3R1kfNCHIyMl1mbyXOZNNdQDkvd+cSPHAUm6YL60Vq/zbUtSj/6qgJEUjsAVrRDctxQgQpOmwv6caeOTwDVKdq6CFRObYmQO9GfW+3ZauvRXEWLpHjwrkLuUxeB0T6aXquoJVFcBhLoju50LGaSkDWkf83sFhNn/3mzErapM/5oyxfXD8VB1B7AC2yFuGyvEIRD6Kcd3cRm5ucZSLTtiNMhtSnslgN+dGpWMjdzKuogB4x/7VyTKyudr1NmChr+iVpvkNNzAUU176I=
    - stage: UI tests
      script:
      - curl -s http://my-feedback-team-b-staging.herokuapp.com > /dev/null
      - yarn test:staging:uitests
    - stage: deploy to production
      if: branch = deploy-to-prod
      script: yarn build
      deploy:
        <<: *heroku
        app: my-feedback-team-b
        on:
          branch: deploy-to-prod

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
- export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  slack:
    secure: hWiZG5Tofh5Qw/LNkJi2+aIG9acd38dC73byrogZs0OGRVdvgXH93mqnnTLNaG5o7+A7Kz2mgc7gxmwQFuxW/qthF1KSX+PAIR+1Y1RE0fx3fI6dNNVvGpFun8jcXpcDvCYYvXCnYgg4ahW+Xch7sL82dpe8keVhMagU0PuoRvPA3iKIVcmc1ldvWDe+agtQ0cWalsuvOld3OUKYwA/hyFSrMmYddKfAIDZzpu/ozOXqXpzXnxXckyM/NgeHCKgCoChKIx0gwFnM6qCqKcYW102hO3iikibsvfwv3syYUYkPYG10vtEd9QGYbbXXskA6T/0Ireyp1kzZjrWhOPjjX7e8wzd7CC8MM9Pf+pyExb5WQOA46n71i8iwfnf+B9zWCYiW3vpoHkvczuplBPGyxW8TpkEzh0S88GWz3tz3rfss2ZJSBT1c1+KHXkRqDvlV3i3JxqlQWSTNDeL7oCqJbI7G80UDeq47iV1k1UX5Fh4SuDry2tB3crlHI/0vjw3l51tRCKIxqINmHt51DTDDLYWKodilCOrn+xMQsdn/qdJGFSDNNIISSAVScXJFNBE4YAc5hJPlb8/6xCz6mHkHVke/ny3NFsfUqFqR8cZ+rwIn5i0V+3MhN7qk7J7GbeSJiDUOS+0ZXnE9fCCHZ0IvFJ6oqdL54QVvsgyvowkmrE8=
