language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  app: my-feedback-team-b-staging
  api_key:
    secure: jKr6t5KhaMx4SQx2ajBM0DuRy1iO10JfCVSXezsPOJKt/dsEIzhSBl1X2hfhZKqvgnBarauOwuILjmNPwXCRtjUAuixJ9mRE2PP58vmRDc0E3qLlHFK6ImPJanwkP7zyJFgh27zPyYvI7PnkMpl8OGCy6LyUZ1KiOP3xEIB8ymnkv/mFe6NReZAZXMpQTXckslyuGyF1Nj1+Jr5ihM2FSVazSt4eD/Xg9ywVtxwmu4dqL2+c8zH+qKEA3T4pmYLNuVE/mXsj2A7v/LTb1WF+shP14XgjXLr1HOEI0t5HXZTXnJL160l6fqp3bRFbeLhQG5ex88X/t8F+d14qpUHD7Mi2EMj/s8jqmL0PvhPyzDcWXwhdTlGk6VPeEUpMnd5QStEGnyKWrPfIRn0SL26FB27fxSDuEY7s5H/w0aUUCqK0ITxCnXFfxWWtHfoIQkefzg5krEGDHXmh5eV/F1a/1NePNsl1JDVn2kqI+/2HXh4mySq+A3/veYnJxWvBUM53+e1UkU+kGQH/MeAc2w1/VgVOPHxhdx14aNf6MfbWPHqxTMmqSw8oOoebiLyAH6/eGhtEak0UtdZDMNFzglfOFO/NzoyuBmT2usNkN3Q7BcyQ8wrX9H//dp1cesiX8oUs/zqDEZfofWqZKGIzSvVq9JOqLSIR16mdPdUt6ZCPSmM=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
notifications:
  slack:
    secure: hWiZG5Tofh5Qw/LNkJi2+aIG9acd38dC73byrogZs0OGRVdvgXH93mqnnTLNaG5o7+A7Kz2mgc7gxmwQFuxW/qthF1KSX+PAIR+1Y1RE0fx3fI6dNNVvGpFun8jcXpcDvCYYvXCnYgg4ahW+Xch7sL82dpe8keVhMagU0PuoRvPA3iKIVcmc1ldvWDe+agtQ0cWalsuvOld3OUKYwA/hyFSrMmYddKfAIDZzpu/ozOXqXpzXnxXckyM/NgeHCKgCoChKIx0gwFnM6qCqKcYW102hO3iikibsvfwv3syYUYkPYG10vtEd9QGYbbXXskA6T/0Ireyp1kzZjrWhOPjjX7e8wzd7CC8MM9Pf+pyExb5WQOA46n71i8iwfnf+B9zWCYiW3vpoHkvczuplBPGyxW8TpkEzh0S88GWz3tz3rfss2ZJSBT1c1+KHXkRqDvlV3i3JxqlQWSTNDeL7oCqJbI7G80UDeq47iV1k1UX5Fh4SuDry2tB3crlHI/0vjw3l51tRCKIxqINmHt51DTDDLYWKodilCOrn+xMQsdn/qdJGFSDNNIISSAVScXJFNBE4YAc5hJPlb8/6xCz6mHkHVke/ny3NFsfUqFqR8cZ+rwIn5i0V+3MhN7qk7J7GbeSJiDUOS+0ZXnE9fCCHZ0IvFJ6oqdL54QVvsgyvowkmrE8=
